### PR TITLE
Fix no class def found error

### PR DESCRIPTION
**Pull request by rchicoli**
Hi there
I've had a problem using this plugin in a Linux system, for whatever reason a bean could not be instantiated.

Funny enough, it works perfectly fine in a windows environment.

Here is the stacktrace I got:
```bash
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mainService' defined in URL [jar:../com.github.qwazer/markdown-confluence-gradle-plugin/0.9.2/a7bf3b4939779f48f3f963a14824ea49fc020671/markdown-confluence-gradle-plugin-0.9.2.jar!/com/github/qwazer/markdown/confluence/core/service/MainService.class]: Unsatisfied dependency expressed through constructor parameter 2; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pageService' defined in URL [jar:.../com.github.qwazer/markdown-confluence-gradle-plugin/0.9.2/a7bf3b4939779f48f3f963a14824ea49fc020671/markdown-confluence-gradle-plugin-0.9.2.jar!/com/github/qwazer/markdown/confluence/core/service/PageService.class]: Unsatisfied dependency expressed through
constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'confluenceService' defined in URL [jar:file:.../com.github.qwazer/markdown-confluence-gradle-plugin/0.9.2/a7bf3b4939779f48f3f963a14824ea49fc020671/markdown-confluence-gradle-plugin-0.9.2.jar!/com/github/qwazer/markdown/confluence/core/service/ConfluenceService.class]: Unsatisfied
dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'restTemplate' defined in com.github.qwazer.markdown.confluence.core.SpringConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.client.RestTemplate]: Factory method 'restTemplate' threw exception; nested exception is java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/exc/InvalidDefinitionException
```

The solution was simply to add jackson-databind to the dependencies. Besides that I optimized the imports, I hope it is all fine.

Great project.

### CODE REVIEW

**Comment by qwazer** [comment]
Thanks!

**Comment by bevintang** [comment]
Hi! Any updates on when the next release is? I could really use this fix!

**Comment by colossal20** [comment]
I am experiencing a similar issue where some of the beans are not being initialized with the same error as posted above. Is there a plan to release this soon ?

**Comment by qwazer** [comment]
Yes, I have such plans, but need to make a lot of infrastructure work to release
1) move out of bintray
2) update to recent gradle
3) update all deps
4) fix tests

Cannot promise any timelines. It is a hobby project.

**Comment by qwazer** [comment]
to #29

**Pull request merged**
