### PR TITLE
Added support for authenticating Confluence API calls with Personal Access Tokens (PATs).

### PR DESCRIPTION
**Pull request by jigga**
…ccess Tokens (PATs).

### CODE REVIEW

**Comment by qwazer** [comment]
Hi! Thanks for the PR.
Please add new config option to README.md in 2 places: 1) sampe config 2) table with list of options

**Comment by qwazer** [comment]
Also, just FYI. I'm work on https://github.com/md2conf/md2conf as a new tool to publish stuff to an Confluence.

**Comment by jigga** [comment]
Thanks for the comments, I've updated the code according to your suggestions. I also added 2 simple tests for verifying the value of the Authorization header sent when making calls to the Confluence APIs.

**Comment by jigga** [comment]
Also, I will probably switch to using the new tool, however, this will take me some time, and in the meantime, it would be super helpful for me to have the proposed changes integrated and a new version of the plugin published.

**Comment by qwazer** [comment]
Merged.
It's need some infrastructure work to release a new version, since old CI scripts are obsolete.

**Comment by jigga** [comment]
Thanks vm.

Is there anything I could do on my end to help with the build/release
infrastructure? Not really sure how the release/publish process works here,
but I could do some research if needed.

Arek

**Comment by qwazer** [comment]
Thanks for attempt to help.
The main problem is the https://bintray.com/qwazer/maven doesn't accept new packages.
Need to switch to maven central for example. 
Since I'm not user of gradle for several years so priority of this work for me is very low.


So I have 2 options:
1) setup a new package repo for this project. But I'm lazy to do it, to be honest
2) create a new gradle plugin for md2conf/mdconf. It's more attractive for me. I have account for my md2conf/mdconf organization in maven central. But, since I'm not user of gradle... )))

I added you to collaborator of this project. So if you find a replacement of a bintray repo hosting and create the account, setup all stuff for public release - you are welcome. 

See https://github.com/qwazer/markdown-confluence-gradle-plugin/blob/master/how-to-release.md

I have access to https://plugins.gradle.org/ so I can do final publishing in `plugins.gradle.org`

**Comment by jigga** [comment]
Hey,

Do we even need to publish it to Maven Central?

I think that if we only publish it to Gradle's plugin portal it should be
available to use by anyone interested in the plugin.

Gradle's users typically use a separate repo for the plugins, so honestly I
don't see any real benefit of publishing to to Maven Central.

What do you think?

BTW, I did the initial release ceremony (updated gradle.properties, tagged
and pushed).

Arek

**Comment by jigga** [comment]
Hi,

Could you help publish the new version of the plugin to the Gradle plugin
portal?

The group id is managed by your account, and hence I cannot publish it
myself.

I already raised the ticket to also publish it to the Central (
https://issues.sonatype.org/browse/OSSRH-92586), however, I'm not sure how
long it will take, and having it in the Gradle's plugin portal would help
me tremendously.

Thanks ,
Arek

**Comment by jigga** [comment]
Hi,

Yet another follow-up, namely:

Invalid groupId, *com.github.* Group IDs are invalid now. The only allowed
groupIds for Github projects are io.github.**

io.github.qwazer would be valid based on your Project URL.

To continue the registration process, please follow these steps:


   1. Create a temporary, public repository called
      https://github.com/qwazer/OSSRH-92586 to verify github account
      ownership.
      2. *Edit this ticket*, update the Group ID field with the new
      GroupId, and set Status to Open.

More info: https://central.sonatype.org/publish/requirements/coordinates/

Could you create the public repo under your account to confirm account
ownership?

Thanks!

**Comment by jigga** [comment]
Hi qwazer,

Any chance you'd be able to help with this?

Or shall I publish it under a different group id?

Thanks,
Arek

**Comment by qwazer** [comment]
Hi
Sorry for delay in answers

I created https://github.com/qwazer/OSSRH-92586

I see 2 basic options here
1) continue with maven central and renaming to io.github.qwazer namespace
2) publish to any maven repo. I think "github-packages-registry" fit these needs. But need research. https://docs.github.com/en/packages/working-with-a-github-packages-registry

I vote for number 2.

**Comment by qwazer** [comment]
Looks like 2 is not the option, because  is useless  because clients cannot download artifacts from Github Package Registry without authorization

**Comment by qwazer** [comment]
The next first googled alternative to bintray is https://jitpack.io/

**Comment by qwazer** [comment]
@jigga released.
Please check!

**Comment by jigga** [comment]
Awesome, thanks very much for your help with this.

I checked, new version is available. Will verify that the changes work in
the wild and will come back with an update.

Arek

**Pull request merged**
